name: Update Minecraft Manifest

# Controls when the workflow will run
on:
  # run ever two hours
  schedule:
    - cron: 5 * * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run app update scripts
        run: |
          sudo apt update
          sudo apt install moreutils jq -y
          cd $GITHUB_WORKSPACE || exit 1
          ./mc-parse-script.sh

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          default_author: github_actions
